* Automatically created file, please enter changes into beam.xls
SET b "All nodes" /
                
FER_UZB         
SYR_UZB         
CHI_UZB         
SUR_UZB         
KAS_UZB         
ZAR_UZB         
SOU_UZB         
SYR_KAZ         
CHI_KAZ         
NOR_KAZ         
AMU_TUR         
SOU_TUR         
FER_KYR         
FER_TAD         
UPA_TAD         
ZAR_TAD         
UPA_AFG         
Res_KAM         
Res_TOK         
Res_AND         
Res_KAR         
Res_CHA         
Res_SHA         
Res_ROG         
Res_NUR         
Res_TMP         
Res_DAS         
Res_ZAR         
Res_FER         
Res_TMR         
Res_AHA         
Res_ARN         
Res_KOK         
Res_ARY         
Res_KAF         
Res_ZD          
Res_TUR         
Res_SUR         
Res_KAS         
Res_TAL         
Res_BUK         
Res_NAR         
Res_FAR         
Res_VAH         
Res_CHI         
Src_TOK         
Src_NAR         
Src_AND         
Src_KAR         
Src_FER         
Src_SYR         
Src_AHA         
Src_CHI         
Src_KEL         
Src_ARY         
Src_ROG         
Src_VAH         
Src_PYD         
Src_KAF         
Src_ZAR         
Src_SUR         
Src_KAS         
Src_AFG         
Src_TUR         
NARYN           
KRDRYA          
SYRFER          
SYRMID          
KELES           
SYRDW1          
SYRDW2          
VAKHSH          
PYANDJ          
KUNDUZ          
KARFIR          
AMUUPS          
AMUMID          
AMUDWN          
Lak_AYD         
Lak_SYR         
Lak_GOL         
Lak_AMU         
Lak_ARS         
Lak_ARN         
/;

SET sea(b) "Lake nodes" /
                
Lak_AYD         
Lak_SYR         
Lak_GOL         
Lak_AMU         
Lak_ARS         
Lak_ARN         
/;

SET c "Countries" /
                
UZB             
KAZ             
TUR             
TAD             
KYR             
AFG             
/;

SET j "Economic sectors" /
                
cot             
wht             
ric             
fru             
veg             
alf             
oth             
fal             
/;

SET resNew(b) "New reservoirs " /
                
res_DAS         
res_ROG         
res_KAM         
res_ZAR         
res_NAR         
res_VAH         

/;

